# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 06:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20151216_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='asignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
